trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'lneArmServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show --verbose'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'lneArmServiceConnection'
  displayName: 'Terraform Apply'
